name: Daily Green Square Bot

on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 0 * * *' # Runs every day at 12:30 AM UTC
  workflow_dispatch:      # Allows you to click a button to run it manually

permissions:
  contents: write

jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Make a Change
        run: |
          date > last_run_date.txt
          
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action Bot"
          git config --global user.email "actions@github.com"
          git add last_run_date.txt
          git commit -m "Daily green square: $(date)"
          git push